### ISSUE TITLE
Kulp Controllers not working when purchesed thru wiredwatts

### ISSUE THREAD

**Issue by jlarsonomaha** [KulpLights/fpp-FPPMon#5]
I have a K16 that I have setup as a remote and it is not showing up in FPPMON. When I unplug the network it does send me a error that it cannot ping that unit from the master Pi.

**Comment by dkulp** [comment]
Can you double check that you have the latest version of FPPMon installed.   This should have been fixed in the 1.0.1 version.

**Comment by jlarsonomaha** [comment]
I did verify that I was on the latest for both the client and master. I have rebooted it all. I also verified the app was up to date.

**Comment by dkulp** [comment]
I pushed a new version of FPPMon for both Android and iOS.  Can you check to see if that works for you?

**Comment by jlarsonomaha** [comment]
I just updated the android app and both the master and remote controller. Rebooted all items and still no remote.

**Comment by dkulp** [comment]
Can you try again?  Rolled out another 1.0.3 update.

**Comment by jlarsonomaha** [comment]
I now see the K16 controller.   Thank You.
