### ISSUE TITLE
Login Fails, previously constantly getting logged out.

### ISSUE THREAD

**Issue by AdeptChild** [KulpLights/fpp-FPPMon#6]
Cannot log in, once info is filled out, clicking login button, it just resets the info fields. started 20 Sept 23.

**Comment by dkulp** [comment]
I was just able to logout and login again.  I'm also seeing other logins from other people in the logs.   Thus, the services appear to be running.   Can you double check to make sure you have the latest version of the plugin installed (from the FPP plugin manager) as there were a couple of enhancements to the login stuff done last week.

**Comment by AdeptChild** [comment]
I did, I updated it earlier this week, i was constantly getting logged out at first, then went away with the update. Now it's just the no login, it does do the pause like it trying to but just clears the field's.

**Comment by AdeptChild** [comment]
I also did a restart on FPP and also a hard reboot, running 7.1 on FPP on a Pi4

**Comment by AdeptChild** [comment]
> I was just able to logout and login again. I'm also seeing other logins from other people in the logs. Thus, the services appear to be running. Can you double check to make sure you have the latest version of the plugin installed (from the FPP plugin manager) as there were a couple of enhancements to the login stuff done last week.

Still no dice on my end, have uninstalled on FPP and re installed, tried a different Pi same thing. also checked and made sure i was using the correct info on Kulp storefront and all is the same.

**Comment by dkulp** [comment]
Can you make sure you turn off any wacky windows security filters or add blockers and such?  I had one user that had issues until they did that.    I'm not see any invalid login attempts for you in the logs so I'm wondering if it's being completely blocked someplace.

**Comment by AdeptChild** [comment]
Did everything I could think of, turned off firewall, all the add crap on edge, pretty much everything, still nothing. ill keep poking at it, unless you have any other idea's.

**Comment by jefft0825** [comment]
Same issue here - i have tried changing my password on the Kulp site - tried using multiple browsers even using my phone.    It will not log me in at all.

**Comment by bobreese** [comment]
I logged out and back in on my Pi with no issues.

**Comment by jefft0825** [comment]
What do you mean logged out?   I can't login

**Comment by bobreese** [comment]
Do you have a logon to Kulp Lights?
Its the same user name and password in the Plugin.

![Kulp 01](https://github.com/KulpLights/fpp-FPPMon/assets/461610/c4a11764-7edf-44af-8f58-aedec6a5a4c5)
![Kulp 02](https://github.com/KulpLights/fpp-FPPMon/assets/461610/b9b5d00a-7e2c-46ff-9d2e-173a9e0a4e41)

**Comment by AdeptChild** [comment]
> Do you have a logon to Kulp Lights? Its the same user name and password in the Plugin.
> 
> ![Kulp 01](https://user-images.githubusercontent.com/461610/271994149-c4a11764-7edf-44af-8f58-aedec6a5a4c5.jpg) ![Kulp 02](https://user-images.githubusercontent.com/461610/271994165-b9b5d00a-7e2c-46ff-9d2e-173a9e0a4e41.jpg)

I know I’m using the correct password and user name, Dan said that he wasn’t seeing any attempts cor login on my end. I also changed my password and tried different browsers, and a totally different pi. After I tried the different setting with firewalls and security settings I haven’t had a chance to mess with it anymore.

**Comment by jefft0825** [comment]
Yes.  I can login to Kullman site without an issue.   Cannot login under FPP

**Comment by dsw-solutions** [comment]
I'm having the same issue. I can log into the Kulp site but not the FPP plugin. When I click the login button I can see it getting a token but the page just refreshes and displays the login button again.
![image](https://github.com/KulpLights/fpp-FPPMon/assets/67870268/692c3fb8-d516-49f0-a1d1-29d3ee1b5c7f)
![image](https://github.com/KulpLights/fpp-FPPMon/assets/67870268/90e0c8e2-c610-4e73-a8d6-8e7d13bb4c8f)

**Comment by AdeptChild** [comment]
> I'm having the same issue. I can log into the Kulp site but not the FPP plugin. When I click the login button I can see it getting a token but the page just refreshes and displays the login button again.
> 
> ![image](https://github.com/KulpLights/fpp-FPPMon/assets/67870268/692c3fb8-d516-49f0-a1d1-29d3ee1b5c7f)
> 
> ![image](https://github.com/KulpLights/fpp-FPPMon/assets/67870268/90e0c8e2-c610-4e73-a8d6-8e7d13bb4c8f)
> 
> 

I haven't figured this out yet myself, granted I haven't had a real chance to really get into it.

**Comment by dkulp** [comment]
Once the browser gets the token, it then needs to send it to the FPP instance.   Can you check the ~fpp/media/config/plugin.fppMon.json file to see if the two tokens (and username) are getting updated in that file?   If not, then there is some issue with the browser->FPP communication.

**Comment by dsw-solutions** [comment]
It appears to be updating that file and the token and user match.
![image](https://github.com/KulpLights/fpp-FPPMon/assets/67870268/449d5da3-3efe-477b-81f4-2b66fcdaa5bc)
![image](https://github.com/KulpLights/fpp-FPPMon/assets/67870268/42d7cd15-467d-47fe-9470-6c7741479512)

**Comment by dsw-solutions** [comment]
It looks like that it goes to /api/plugin-apis/FPPMon/credentials after that and that returns a status of ok there. Although I tried posting an invalid token to there and it still says ok.
![image](https://github.com/KulpLights/fpp-FPPMon/assets/67870268/8d140f27-a114-4dc0-b1e8-87f1dfc21794)

![image](https://github.com/KulpLights/fpp-FPPMon/assets/67870268/d5cf1117-345a-4e3f-8abe-00bb1ff1a9f3)

**Comment by AdeptChild** [comment]
Anyone figure this out yet, I finally have the time to sit down and mess with this more.
So far I have:
Using Edge- removed all browsing safety, opened fire-wall ect., no dice
Have also used other browsers and my phone as well.

**Comment by AdeptChild** [comment]
So I have mine working: 
I actually had a spare pi loaded a fresh image of FPP on it, and it logged in fine. With my browser (edge). 
So with that I believe it was something on my main player pi that isn't right. So if anyone is still having this issue, maybe backup and re image may solve the problem.

**Comment by dsw-solutions** [comment]
I updated mine to 7.3.1 and mine is working now too.

**Comment by AdeptChild** [comment]
> I updated mine to 7.3.1 and mine is working now too.

Awesome, I think I'm just gonna leave it running on that spare pi till after the season, then I'll reflash my player.

**Comment by AdeptChild** [comment]
Forgot to add also: looks like it was more of a DNS issue, I static all my Pi's after setting my DNS setting (8.8.8.8) I lost ability to log in. Set back to DHCP started working again.
