### ISSUE TITLE
Logged out after reboot or power cycle on a pi

### ISSUE THREAD

**Issue by PiSignage** [KulpLights/fpp-FPPMon#8]
Hi, 
Once I reboot or power cycle on my pi FPPMON don't log back in on FPP. I have to log back on manually for it to work again.
I am running FPP 7.2 connected over wifi to the internet.

**Comment by bobreese** [comment]
I can confirm this issue.
Upgraded from 7.1, every reboot after 7.2 installed causes the plugin to need login info....
Did check for a plugin update, none available

[FPP_Logs_20231008.1114.zip](https://github.com/KulpLights/fpp-FPPMon/files/12840483/FPP_Logs_20231008.1114.zip)
![Upgrade 06](https://github.com/KulpLights/fpp-FPPMon/assets/461610/278ba2a7-0aef-460c-98f8-4e56250fdf56)
![Upgrade 07](https://github.com/KulpLights/fpp-FPPMon/assets/461610/52edf54f-f488-4cd4-8980-1a4e5837a762)
![Upgrade 08](https://github.com/KulpLights/fpp-FPPMon/assets/461610/bc38d4f9-9f2b-4382-ac99-e1a13f8325e7)

**Comment by PiSignage** [comment]
I found if i increased the boot delay to 15s all was worked
