### ISSUE TITLE
Allow schedule of monitoring

### ISSUE THREAD

**Issue by brennja** [KulpLights/fpp-FPPMon#9]
My master (pi) is on 24/7. All remotes (Kulps) are only on for the show. Generally, power up Kulps 30 minutes before show.
I would like control of when FPP Monitoring is performed. Currently getting a lot of false alerts between 11pm and 6pm next day.
Maybe a script to start and stop monitoring would be the most flexible for people.

**Comment by dartunder** [comment]
I'm assuming "Monitoring" means "Enable Notifications". 
We would want the device always available via FPPMon

**Comment by brennja** [comment]
Yes control Enable Notifications

**Comment by dkulp** [comment]
I just updated the plugin to add two FPP Commands for enabling/disabling the notifications.   Those can be scheduled as any other FPP command.

**Comment by dartunder** [comment]
FYI I updated the plugin.  The extra commands were not listed.  I restarted still not listed.  I uninstalled the plug-in and reinstalled it and now the extra commands are available.
